language: node_js
node_js:
- 6.9.1
deploy:
  provider: heroku
  api_key:
    secure: o5A3lLODax7qHUgit9LJyO+L0ySKE0Hjy7vkUuxFDOUTv+5gLKzwb/tFFYZcezVR1Tn2aQgKJcEgXiD+0MBWj9tfDtSfofGDBbc1/qRnYbZqwv1EAGRIMuSnxtpb36LIsKCSI1V1CU2N1XjQ7fMEVzOhyCNdNPz2YHTlvDSiNpV6Zf5wCBTVpAg8O9EQm22L0rDP2mmkbqIWMs1fWNHpu8V9bEc0Za7upq156WZDxua6X6H0tOIQNaPNrAGaYeqIa0KbsN04++zMaPOVElBI/KBMsCIo3qN5B5YKNkuOzrTNHxE639NArBrGM1yw9cHQ+5mEb+Z3sPxNTt+XQSlbseymOtMUl43TbU48KgVWETLOdZtb1O9g32cOC8pm7ZO7eSRfVFdRH1z6/l9K1YxQ8ixuRamxnI9OSXpyDUe0nCzRmC9L3/vjJd5dcoty9XCleQtdc3cK9NGnorFfBanpWVVdGj8Eq6IUQwO616Cl9LXWwDkaXh9BiRnZjAcpZP7UT4DaruPw1An3ONs8reZ0BC90yRAVo6QPcMwZ4lSTHS1z04tih+kHp31kSWkpExkMjqP9OdpKIvfHwMyL7amJ2ktl3JBCRHyOp8aXEv8lQ1/ARsYfW2ZlROKoS22FRqLFm59gC6uyq0tI6bLeZ9JurVmN7eoPAIza/45ipfg8LOc=
  app: doghouseio
